import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // docs: ['doc1', 'mdx'],
  // base: [{ type: 'autogenerated', dirName: 'base' }],
  // js: [{ type: 'autogenerated', dirName: 'js' }],
  // interview: [{ type: 'autogenerated', dirName: 'interview' }],
  // interview2021: [
  //   'interview2021/stack',
  //   'interview2021/proto',
  //   'interview2021/variant',
  //   'interview2021/event-loop',
  //   'interview2021/promise',
  //   'interview2021/react',
  // ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
}

export default sidebars
